name: paperless_mobile_document_scanner
description: "A new Flutter plugin project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0
  flutter: ">=3.3.0"

dependencies:
  camera: ^0.12.0+1
  flutter:
    sdk: flutter
  opencv_dart: ^2.2.1+4
  path: ^1.9.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

hooks:
  user_defines:
    dartcv4:
      debug: false
      include_modules: # `core` is always included
        - imgcodecs
        - imgproc
