//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:json_annotation/json_annotation.dart';

/// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
enum RuleTypeEnum {
  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(0)
  number0('0'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(1)
  number1('1'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(2)
  number2('2'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(3)
  number3('3'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(4)
  number4('4'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(5)
  number5('5'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(6)
  number6('6'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(7)
  number7('7'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(8)
  number8('8'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(9)
  number9('9'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(10)
  number10('10'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(11)
  number11('11'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(12)
  number12('12'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(13)
  number13('13'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(14)
  number14('14'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(15)
  number15('15'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(16)
  number16('16'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(17)
  number17('17'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(18)
  number18('18'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(19)
  number19('19'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(20)
  number20('20'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(21)
  number21('21'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(22)
  number22('22'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(23)
  number23('23'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(24)
  number24('24'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(25)
  number25('25'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(26)
  number26('26'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(27)
  number27('27'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(28)
  number28('28'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(29)
  number29('29'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(30)
  number30('30'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(31)
  number31('31'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(32)
  number32('32'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(33)
  number33('33'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(34)
  number34('34'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(35)
  number35('35'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(36)
  number36('36'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(37)
  number37('37'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(38)
  number38('38'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(39)
  number39('39'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(40)
  number40('40'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(41)
  number41('41'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(42)
  number42('42'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(43)
  number43('43'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(44)
  number44('44'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(45)
  number45('45'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(46)
  number46('46'),

  /// * `0` - title contains * `1` - content contains * `2` - ASN is * `3` - correspondent is * `4` - document type is * `5` - is in inbox * `6` - has tag * `7` - has any tag * `8` - created before * `9` - created after * `10` - created year is * `11` - created month is * `12` - created day is * `13` - added before * `14` - added after * `15` - modified before * `16` - modified after * `17` - does not have tag * `18` - does not have ASN * `19` - title or content contains * `20` - fulltext query * `21` - more like this * `22` - has tags in * `23` - ASN greater than * `24` - ASN less than * `25` - storage path is * `26` - has correspondent in * `27` - does not have correspondent in * `28` - has document type in * `29` - does not have document type in * `30` - has storage path in * `31` - does not have storage path in * `32` - owner is * `33` - has owner in * `34` - does not have owner * `35` - does not have owner in * `36` - has custom field value * `37` - is shared by me * `38` - has custom fields * `39` - has custom field in * `40` - does not have custom field in * `41` - does not have custom field * `42` - custom fields query * `43` - created to * `44` - created from * `45` - added to * `46` - added from * `47` - mime type is
  @JsonValue(47)
  number47('47');

  const RuleTypeEnum(this.value);

  final String value;

  @override
  String toString() => value;
}
